import { Link } from '@mui/material'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Match Emojis !!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <Link href="/tiles?level=1">This Cool App</Link>
        </h1>

        <p className={styles.description}>
          Get started by clicking on{' '}
          <code className={styles.code}>↑ This Cool App ↑ </code>
        </p>

        <div className={styles.grid}>
          <Link href="/tiles?level=10" className={styles.card}>
            <h2>Level 10 &rarr;</h2>
            <p>Too lazy to start from level 1 ? Click here to jump to level 10</p>
          </Link>

          <Link href="/tiles?level=20" className={styles.card}>
            <h2>Level 20 &rarr;</h2>
            <p>Enjoying our interactive mini-game ? Click here to jump to level 20</p>
          </Link>

          <Link
            href="/tiles?level=30"
            className={styles.card}
          >
            <h2>Level 30 &rarr;</h2>
            <p>Discover more features by jumping to level 30</p>
          </Link>

          <Link
            href="/tiles?level=40"
            className={styles.card}
          >
            <h2>Level 40 &rarr;</h2>
            <p>
              Do you seek a greater challenge ? try level 40
            </p>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
